import ctypes

__all__ = ('ALL_CONSTANTS', 'RLIMIT_AS', 'RLIMIT_CORE', 'RLIMIT_CPU', 'RLIMIT_DATA', 'RLIMIT_FSIZE', 'RLIMIT_MEMLOCK', 'RLIMIT_NOFILE', 'RLIMIT_NPROC', 'RLIMIT_RSS', 'RLIMIT_STACK', 'RLIM_INFINITY', 'RLIM_NLIMITS', 'RUSAGE_CHILDREN', 'RUSAGE_SELF', 'rlim_t', 'rlim_t_max')

ALL_CONSTANTS = ('RLIM_INFINITY', 'RLIM_NLIMITS', 'RLIMIT_CPU', 'RLIMIT_FSIZE', 'RLIMIT_DATA', 'RLIMIT_STACK', 'RLIMIT_CORE', 'RLIMIT_RSS', 'RLIMIT_NPROC', 'RLIMIT_NOFILE', 'RLIMIT_MEMLOCK', 'RLIMIT_AS', 'RUSAGE_SELF', 'RUSAGE_CHILDREN')
RLIMIT_AS = 5
RLIMIT_CORE = 4
RLIMIT_CPU = 0
RLIMIT_DATA = 2
RLIMIT_FSIZE = 1
RLIMIT_MEMLOCK = 6
RLIMIT_NOFILE = 8
RLIMIT_NPROC = 7
RLIMIT_RSS = 5
RLIMIT_STACK = 3
RLIM_INFINITY = 9223372036854775807
RLIM_NLIMITS = 9
RUSAGE_CHILDREN = -1
RUSAGE_SELF = 0
rlim_t = ctypes.c_ulong
rlim_t_max = 18446744073709551615
