import ctypes

__all__ = ('ALL_CONSTANTS', 'RLIMIT_AS', 'RLIMIT_CORE', 'RLIMIT_CPU', 'RLIMIT_DATA', 'RLIMIT_FSIZE', 'RLIMIT_LOCKS', 'RLIMIT_MEMLOCK', 'RLIMIT_MSGQUEUE', 'RLIMIT_NICE', 'RLIMIT_NOFILE', 'RLIMIT_NPROC', 'RLIMIT_OFILE', 'RLIMIT_RSS', 'RLIMIT_RTPRIO', 'RLIMIT_SIGPENDING', 'RLIMIT_STACK', 'RLIM_INFINITY', 'RLIM_NLIMITS', 'RUSAGE_CHILDREN', 'RUSAGE_SELF', 'rlim_t', 'rlim_t_max')

ALL_CONSTANTS = ('RLIM_INFINITY', 'RLIM_NLIMITS', 'RLIMIT_CPU', 'RLIMIT_FSIZE', 'RLIMIT_DATA', 'RLIMIT_STACK', 'RLIMIT_CORE', 'RLIMIT_RSS', 'RLIMIT_NPROC', 'RLIMIT_NOFILE', 'RLIMIT_OFILE', 'RLIMIT_MEMLOCK', 'RLIMIT_AS', 'RLIMIT_LOCKS', 'RLIMIT_SIGPENDING', 'RLIMIT_MSGQUEUE', 'RLIMIT_NICE', 'RLIMIT_RTPRIO', 'RUSAGE_SELF', 'RUSAGE_CHILDREN')
RLIMIT_AS = 9
RLIMIT_CORE = 4
RLIMIT_CPU = 0
RLIMIT_DATA = 2
RLIMIT_FSIZE = 1
RLIMIT_LOCKS = 10
RLIMIT_MEMLOCK = 8
RLIMIT_MSGQUEUE = 12
RLIMIT_NICE = 13
RLIMIT_NOFILE = 7
RLIMIT_NPROC = 6
RLIMIT_OFILE = 7
RLIMIT_RSS = 5
RLIMIT_RTPRIO = 14
RLIMIT_SIGPENDING = 11
RLIMIT_STACK = 3
RLIM_INFINITY = 18446744073709551615
RLIM_NLIMITS = 16
RUSAGE_CHILDREN = -1
RUSAGE_SELF = 0
rlim_t = ctypes.c_ulong
rlim_t_max = 18446744073709551615
