
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.11.1'
version_full = '7b287a013c1bcd2d5c02bb7e15c4304d22f97681'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

